//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demand()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public int idDemand { get; set; }
        public int idClient { get; set; }
        public int idAgent { get; set; }
        public string typeEstate { get; set; }
        public Nullable<int> minPrice { get; set; }
        public Nullable<int> maxPrice { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string apartment { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> minArea { get; set; }
        public Nullable<decimal> maxArea { get; set; }
        public Nullable<int> minTotalRooms { get; set; }
        public Nullable<int> maxTotalRooms { get; set; }
        public Nullable<int> minFloor { get; set; }
        public Nullable<int> maxFloor { get; set; }
        public Nullable<int> minTotalFloors { get; set; }
        public Nullable<int> maxTotalFloors { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deals { get; set; }
    }
}
