//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstateObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstateObject()
        {
            this.Sentences = new HashSet<Sentence>();
        }
    
        public int idEstate { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string addressNumber { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<int> totalFloors { get; set; }
        public Nullable<decimal> totalArea { get; set; }
        public Nullable<int> rooms { get; set; }
        public Nullable<int> floor { get; set; }
        public string typeEstate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sentence> Sentences { get; set; }
    }
}
